### ISSUE TITLE
This is incredible!! Thank you <3 Can I donate in any way?

### ISSUE THREAD

**Issue by modusmogulus** [kazeraniman/GalaxyGravity#1]

**Comment by kazeraniman** [comment]
Hey there,

I'm glad you liked it! It genuinely makes me ecstatic that someone enjoyed something I created. Now I feel kind of guilty though for not giving more love to the code in some places haha.

As for the original question, while I am flattered I am not accepting donations at this time. I am more than happy to just to receive your comments and stars and such. If you do want to donate, I would recommend donating to those in need through a trustworthy charity, or alternatively you could buy something for someone you care about and make their day too!

Thanks again!
